language: node_js

sudo: false

node_js:
  - "10"

before_install:
  - sudo apt-get install -y python python-dev
  - pip install --user pipenv

cache:
  apt: true
  directories:
    - node_modules

script:
  - npm run build

deploy:
  provider: script
  script: .travis/deploy.sh
  skip_cleanup: true
  on:
    branch: master
