language: node_js

sudo: false

node_js:
  - "10"

python:
  - "3.7-dev"

cache:
  apt: true
  directories:
    - node_modules

script:
  - npm run build

deploy:
  provider: script
  script: .travis/deploy.sh
  skip_cleanup: true
  on:
    branch: master
