title: Ant-Home
subtitle: "Ant blog."
description: "一起学习，一起进步."
author: Zhu Yanlei
language: zh-cn
timezone: UTC
url: https://ant-sir.github.io/
root: /
permalink: news/:year/:month/:day/:title/
archive_dir: news
code_dir: downloads/code
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
highlight:
  enable: true
  line_number: false
per_page: 0

theme: navy
deploy:
  type: git
  repo: git@github.com:ant-sir/ant-sir.github.io.git

disqus_shortname: antsir
google_analytics: UA-61377615-1
fb_admins: 100000247608790
algolia:
  zh-cn:
    api_key: 67a88d44602c73798fc38f7269ef7053
    index_name: iopencloud
twitter: antcoder
weibo: 5301170870
github: ant-sir/site
