title: Ant-Home
subtitle: "Ant blog."
description: "一起学习，一起进步."
author: Zhu Yanlei
language: zh-cn
timezone: UTC

url: https://ant-sir.github.io/
root: /
permalink: :year/:month/:day/:title/
code_dir: downloads/code
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
per_page: 0

theme: navy
deploy:
  type: git
  repo: git@github.com:ant-sir/ant-sir.github.io.git

highlight:
  enable: true
  line_number: false

disqus_shortname: antsir
google_analytics: UA-61377615-1

weibo: 5301170870
github: ant-sir/site
