<footer id="footer" class="wrapper">
  <div class="inner">
    <div id="footer-copyright">
      &copy; {{ moment(Date.now()).year() }} <a href="https://ant-sir.github.io/" target="_blank">{{ config.author }}</a><br>
      Documentation licensed under <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank">CC BY 4.0</a>.
    </div>
    <div id="footer-links">
      <a href="https://weibo.com/{{ config.weibo }}" class="footer-link" target="_blank"><i class="fa fa-weibo"></i></a>
      <a href="https://github.com/{{ config.github }}" class="footer-link" target="_blank"> <i class="fa fa-weixin" aria-hidden="true"></i></a>
      <a href="https://github.com/{{ config.github }}" class="footer-link" target="_blank"> <i class="fa fa-qq" aria-hidden="true"></i></a>
      <a href="https://github.com/{{ config.github }}" class="footer-link" target="_blank"><i class="fa fa-github-alt"></i></a>
    </div>
  </div>
</footer>
